config/routes.rb
Rails.application.routes.draw do
  root "places#index"

  resources :places
  resources :entries
  resources :users, only: [:new, :create]

  get 'login', to: 'sessions#new'
  post 'sessions', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :place
  belongs_to :user

  has_one_attached :image

  validates :title, presence: true
  validates :description, presence: true
  validates :occurred_on, presence: true
end

app/models/place.rb
class Place < ApplicationRecord
  has_many :entries, dependent: :destroy

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :entries, dependent: :destroy

  validates :username, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_user
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authenticate_user!
    redirect_to login_path unless current_user
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!

  def new
    @entry = Entry.new(place_id: params[:place_id])
  end

  def create
    @entry = current_user.entries.new(entry_params)
    if @entry.save
      @entry.image.attach(params[:entry][:image])
      redirect_to place_path(@entry.place_id), notice: "Entry created successfully"
    else
      render :new
    end
  end

  private

  def entry_params
    params.require(:entry).permit(:title, :description, :occurred_on, :place_id, :image)
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!

  def index
    @places = Place.all
  end

  def show
    @place = Place.find(params[:id])
    @entries = @place.entries.where(user_id: current_user.id)
  end

  def new
    @place = Place.new
  end

  def create
    @place = Place.new(place_params)
    if @place.save
      redirect_to places_path, notice: "Place added successfully"
    else
      render :new
    end
  end

  private

  def place_params
    params.require(:place).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to places_path, notice: "Logged in successfully"
    else
      flash.now[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: "Logged out successfully"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to "/", notice: "User created successfully"
    else
      puts @user.errors.full_messages # Log validation errors
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= form_with model: @entry, url: entries_path, method: :post, local: true, multipart: true do |form| %>
  <%= form.hidden_field :place_id, value: @entry.place_id %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control', id: 'title_input' %>
  </div>
  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control', id: 'description_input' %>
  </div>
  <div class="form-group">
    <%= form.label :occurred_on %>
    <%= form.date_field :occurred_on, class: 'form-control', id: 'occurred_on_input' %>
  </div>
  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: 'form-control', id: 'image_input', accept: 'image/png, image/jpg, image/jpeg, image/gif' %>
  </div>
  <button type="submit" class="btn btn-primary">Save</button>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travel Journal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Travel Journal</a>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav ml-auto">
          <% if @current_user %>
            <li class="nav-item"><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %></li>
          <% else %>
            <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to 'Signup', new_user_path, class: 'nav-link' %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |key, message| %>
        <div class="alert alert-<%= key == 'alert' ? 'danger' : 'success' %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/places/index.html.erb
<h1>Places</h1>

<ul class="list-group">
  <% @places.each do |place| %>
    <li class="list-group-item">
      <%= link_to place.name, place_path(place) %>
    </li>
  <% end %>
</ul>

<p>
  <%= link_to 'New Place', new_place_path, class: 'btn btn-primary' %>
</p>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= form_with(model: @place, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control', id: 'name_input' %>
  </div>
  <button type="submit" class="btn btn-primary">Save</button>
<% end %>

app/views/places/show.html.erb
<h1><%= @place.name %></h1>

<h2>My Entries</h2>
<div class="row">
  <% @entries.each do |entry| %>
    <div class="col-md-4">
      <div class="card mb-3">
        <div class="card-body">
          <h3 class="card-title"><%= entry.title %></h3>
          <h4 class="card-subtitle mb-2 text-muted"><%= entry.occurred_on %></h4>
          <p class="card-text"><%= entry.description %></p>
          <% if entry.image.attached? %>
            <img src="<%= url_for(entry.image) %>" class="img-fluid">
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<p>
  <%= link_to 'New Entry', new_entry_path(place_id: @place.id), class: 'btn btn-primary' %>
</p>

<p>
  <%= link_to 'Back to All Places', places_path, class: 'btn btn-secondary' %>
</p>

app/views/users/new.html.erb
<h1>New User Account</h1>

<form action="/users" method="post">
  <%= csrf_meta_tags %>
  <div class="form-group">
    <label for="username">Username</label>
    <input type="text" name="user[username]" id="username" class="form-control">
  </div>
  <div class="form-group">
    <label for="email">Email</label>
    <input type="text" name="user[email]" id="email" class="form-control">
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" name="user[password]" id="password" class="form-control">
  </div>
  <button class="btn btn-primary">Signup</button>
</form>